apiVersion: v1
kind: Template
metadata:
  name: image-signing-request-template
  annotations:
    openshift.io/display-name: Image Signing Request Template
    description: Template to create an Image Signing Request
objects:
- apiVersion: "cop.redhat.com/v1alpha2"
  kind: ImageSigningRequest
  metadata:
    name: ${IMAGE_VERIFICATION_REQUEST_NAME}
  spec:
    imageStreamTag: "${IMAGE_STREAM_TAG}"
    signingKeySecretName: "${GPG_SECRET}"
parameters:
- name: IMAGE_SIGNING_REQUEST_NAME
  displayName: Image Signing Request Name
  description: Name of the Image Signing Request
  required: true
- description: ImageStream Tag of the Image to Sign (Format is <imagestream>:<tag>)
  displayName: ImageStream Tag
  name: IMAGE_STREAM_TAG
  required: true
- description: GPG key secret for verifying signed image
  displayName: GPG key secret
  name: GPG_SECRET
  required: true